SocialNetwork/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using SocialNetwork.Models;
using SocialNetwork.Controllers;
using System.Diagnostics;

namespace BootstrapMvcSample.Controllers
{
    public class HomeController : BootstrapBaseController
    {
        private static List<HomeInputModel> _models = ModelIntializer.CreateHomeInputModels();
        public ActionResult Index()
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == null)
            {
                return RedirectToAction("Login", "Account");
            }
            UsersContext db = new UsersContext();
            var username = System.Web.HttpContext.Current.User.Identity.Name;
            var updateslist = Helpers.GetListOfUpdates(username);
            Debug.WriteLine(updateslist.Count());
            try
            {
                Debug.WriteLine(updateslist.FirstOrDefault().data);
            }
            catch
            {
                Debug.WriteLine("The data is empty");
            }
            return View(updateslist);
        }

        [HttpPost]
        public ActionResult Create(string data)
        {
            Updates update = new Updates();

            var username = System.Web.HttpContext.Current.User.Identity.Name;
            var id = Helpers.FetchUserId(username);
            update.data = data;
            update.datecreated = DateTime.Now;
            update.datemodified = DateTime.Now;
            update.status = 1;
            update.userid = id;
            if (ModelState.IsValid)
            {
                Helpers.InsertUpdate(update);
                Success("Status update was successful!");
                return RedirectToAction("Index");
            }
            Error("there were some errors in your form.");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult InsertComment(string commentdata, int updateid)
        {
            var username = System.Web.HttpContext.Current.User.Identity.Name;
            var id = Helpers.FetchUserId(username);
            var comment = new Comments();
            comment.data = commentdata;
            comment.datecreated = DateTime.Now;
            comment.datemodified = DateTime.Now;
            comment.status = 1;
            comment.updateid = updateid;
            comment.userid = id;
            Helpers.InsertComment(comment);
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View(new HomeInputModel());
        }

        public ActionResult Delete(int id)
        {
            _models.Remove(_models.Get(id));
            Information("Your widget was deleted");
            if(_models.Count==0)
            {
                Attention("You have deleted all the models! Create a new one to continue the demo.");
            }
            return RedirectToAction("index");
        }
        public ActionResult Edit(int id)
        {
            var model = _models.Get(id);
            return View("Create", model);
        }
        [HttpPost]        
        public ActionResult Edit(HomeInputModel model,int id)
        {
            if(ModelState.IsValid)
            {
                _models.Remove(_models.Get(id));
                model.Id = id;
                _models.Add(model);
                Success("The model was updated!");
                return RedirectToAction("index");
            }
            return View("Create", model);
        }

		public ActionResult Details(int id)
        {
            var model = _models.Get(id);
            return View(model);
        }


        internal ActionResult Admin()
        {
            // used for demonstrationg route filters
            throw new NotImplementedException();
        }
    }
}

SocialNetwork/Controllers/OperationsController.cs
using SocialNetwork.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialNetwork.Controllers
{
    public class OperationsController : Controller
    {
        //
        // GET: /Operations/

        public ActionResult Profile()
        {
            //Get the logged in username
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var username = System.Web.HttpContext.Current.User.Identity.Name;
            Debug.WriteLine(username);
            UserDetails userdetails = Helpers.GetUserDetails(username);
            //Create the display model
            UserDetailsModel userdetailsmodel = new UserDetailsModel();
            userdetailsmodel.FirstName = userdetails.firstname;
            userdetailsmodel.LastName = userdetails.lastname;
            userdetailsmodel.About = userdetails.about;
            userdetailsmodel.DateOfBirth = userdetails.dateofbirth;
            userdetailsmodel.Gender = userdetails.gender;
            try
            {
                userdetailsmodel.ProfilePic = Helpers.GetUserProfilePic(username).pic;
            }
            catch (Exception ex)
            {
                userdetailsmodel.ProfilePic = null;
            }

            

            if (userdetailsmodel.ProfilePic == null)
            {
                ViewBag.ImagePath = "~/Images/defaultimage.png";

                //Use the default image instead

                using (Image image = Image.FromFile("~/Images/defaultimage.png"))
                {
                    using (MemoryStream m = new MemoryStream())
                    {
                        image.Save(m, image.RawFormat);
                        byte[] imageBytes = m.ToArray();

                        // Convert byte[] to Base64 String
                        // base64String = Convert.ToBase64String(imageBytes);
                        ViewBag.Image = imageBytes;
                    }
                }
            }
            else
            {
                ViewBag.Image = userdetailsmodel.ProfilePic;
            }
            
            return View(userdetailsmodel);
        }
        public ActionResult Notifications()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Upload(UserDetailsModel IG)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            // Apply Validation Here
            //Set the other profile pictures as inactive
            
            //Save the profile image
            if (IG.File.ContentLength > (2 * 1024 * 1024))
            {
                ModelState.AddModelError("CustomError", "File size must be less than 2 MB");
                return RedirectToAction("Profile");
            }
           /* if (!(IG.File.ContentType == "image/jpeg" || IG.File.ContentType == "image/gif"))
            {
                ModelState.AddModelError("CustomError", "File type allowed : jpeg and gif");
                return RedirectToAction("Profile");
            }*/
            Helpers.UpdateProfilePicStatus(System.Web.HttpContext.Current.User.Identity.Name);
            byte[] data = new byte[IG.File.ContentLength];
            IG.File.InputStream.Read(data, 0, IG.File.ContentLength);
            ProfilePics details = new ProfilePics();
            int id = Helpers.FetchUserId(System.Web.HttpContext.Current.User.Identity.Name);
            details.userid = id;
            details.pic = data;
            details.datecreated = DateTime.Now;
            details.datemodified = DateTime.Now;
            details.status = 1;//Status 1 means the profile picture is the active 1.
            using (UsersContext dc = new UsersContext())
            {

                dc.ProfilePics.Add(details);
                dc.SaveChanges();
            }
            return RedirectToAction("Profile");
        }

        public ActionResult NewsFeed()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        //This action is used to search friends and list them
        [HttpPost]
        public ActionResult SearchFriends(string searchstring)
        {
            Debug.WriteLine(searchstring);
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var lstuserdetails = Helpers.SearchFriends(searchstring);
            return View(lstuserdetails);
        }

        [HttpGet]
        public ActionResult InsertFriendRequest(int id)
        {
            Debug.WriteLine(id);
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            int toid = Helpers.FetchUserId(System.Web.HttpContext.Current.User.Identity.Name);
            Helpers.InsertFriendRequest(id, toid);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult GetMessages()
        {
            
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            string username = System.Web.HttpContext.Current.User.Identity.Name;
            var messages=Helpers.ReadMessages(username);
            return View(messages);
        }

        [HttpGet]
        public ActionResult InsertMessages()
        {
            var users = Helpers.GetUsers();
            
            return View(users);
        }

        [HttpGet]
        public ActionResult InsertMessageToDB(int toid, string data)
        {

            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            int fromid = Helpers.FetchUserId(System.Web.HttpContext.Current.User.Identity.Name);
            var message = new Messages();
            message.data = data;
            message.datecreated = DateTime.Now;
            message.datemodified = DateTime.Now;
            message.fromuserid = fromid;
            message.touserid = toid;
            Helpers.InsertMessage(message);
            return RedirectToAction("Index", "Home");
        }
    }
}

SocialNetwork/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

SocialNetwork/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

SocialNetwork/Views/Home/Index.cshtml
@model IEnumerable<SocialNetwork.Models.UpdatesModel>

@{
    ViewBag.Title = "title";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

    
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li>@Html.ActionLink("Home", "Index", "Home")</li>
              <li>@Html.ActionLink("Insert Messages", "InsertMessages", "Operations")</li>
              <li>@Html.ActionLink("Read Messages", "GetMessages", "Operations")</li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
             @using (Html.BeginForm("Create", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary(true)
               
                            <textarea style="width:100%" id="data" name="data" >update status</textarea>
                            @Html.ValidationMessage("CustomError")
                            <br>
                            <input type="submit" value="post" />
                          
            }
                          
                @foreach (var item in Model) {
                    <div>
                        <h6>@item.datecreated by @item.updatename</h6>
                        @item.data
                        <div style="background-color:silver">
                        <h6>comments</h6>
                                      @if (item.comments != null)
                                      {
                                        foreach (var cm in item.comments) {
                                            <div>
                                                <h6>@cm.datecreated by @cm.commentsname</h6>
                                                @cm.data
                                            </div>             

                                        }
                                      }

                                         @using (Html.BeginForm("InsertComment", "Home", FormMethod.Get, new { enctype = "multipart/form-data" }))
                                            {
                                                @Html.ValidationSummary(true)
               
                                                            <textarea style="width:50%" id="commentdata" name="commentdata" >comment</textarea>
                                                            <input type="text" class="hidden" value=@item.updateid name="updateid" id="updateid">  
                                                            @Html.ValidationMessage("CustomError")
                                                            <br>
                                                            <input type="submit" value="comment" />
                          
                                            }
                            </div>
                    </div>
                    <hr/>
                

                }

               
          </div>
          
        </div><!--/span-->
      </div><!--/row-->